name: ${project.name}
version: ${project.version}
main: com.darkender.plugins.containerpassthrough.ContainerPassthrough
api-version: 1.19
author: Techdoodle (Original), RhythmicSys (Fork), Peashooter101 (Fork)